version: "3.8"

services:
  client-app:
    image: solarfarm:client-app-1.0
    build:
      context: .
      dockerfile: solar-farm-fe/Dockerfile
    ports:
      - target: 80
        published: 4200
    volumes:
      - ./Misc/client-app/default.conf:/etc/nginx/conf.d/default.conf:ro

  iot-data-api:
    image: solarfarm:iot-data-api-1.0
    build:
      context: .
      dockerfile: SolarFarm.IotDataApi/Dockerfile
    environment:
      - ConnectionStrings__IotDataContext=Server=database;Database=SolarFarmIot;Trusted_Connection=False;User Id=sa;Password=zaQ@123456!
      - ProducerConfig__BootstrapServers=kafka:29092
      - AdminClientConfig__BootstrapServers=kafka:29092
      - MetabaseUrl=http://localhost:3000
      - MetabaseDashboardSecretKey=192fc6b453a30fbd80d56f86081a52446c85d4291a79682bd8d7caf9b54604e2
    depends_on:
      - database
      - kafka
    ports:
      - target: 80
        published: 5000

  iot-data-handler:
    image: solarfarm:iot-data-handler-1.0
    build:
      context: .
      dockerfile: SolarFarm.IotDataHandler/Dockerfile
    environment:
      - ConnectionStrings__IotDataContext=Server=database;Database=SolarFarmIot;Trusted_Connection=False;User Id=sa;Password=zaQ@123456!
      - ConsumerConfig__BootstrapServers=kafka:29092
    depends_on:
      - database
      - kafka
      - iot-data-api

  kafka:
    image: solarfarm:kafka-1.0
    build:
      context: .
      dockerfile: Misc/kafka/Dockerfile
    volumes:
      - ./Misc/kafka/config:/kafka/config-override
      - ./Misc/kafka/scripts:/kafka/scripts
    ports:
      - target: 9092
        published: 9092

  database:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=zaQ@123456!
      - MSSQL_PID=Express
    ports:
      - target: 1433
        published: 1434

  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./Misc/metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - target: 3000
        published: 3000

networks:
  default:
    name: solarfarm-shared-network
